const styles = {
  container: {
    backgroundColor: '#1e1e1e',
    color: '#ffffff',
    minHeight: '100vh',
    padding: '40px',
    boxSizing: 'border-box',
    '@media (max-width: 768px)': {
      padding: '20px',
    },
  },
  dashboardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '30px',
    maxWidth: '1600px',
    margin: '0 auto',
    '@media (max-width: 768px)': {
      gridTemplateColumns: '1fr',
      gap: '20px',
    },
  },
  dashboardCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '30px',
    '@media (max-width: 768px)': {
      padding: '20px',
    },
  },
  title: {
    color: '#ffffff',
    fontSize: '28px',
    fontWeight: '300',
    letterSpacing: '2px',
    marginBottom: '25px',
    '@media (max-width: 768px)': {
      fontSize: '24px',
      marginBottom: '20px',
    },
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    width: '100%',
    '@media (max-width: 768px)': {
      gap: '15px',
    },
  },
  input: {
    padding: '15px',
    borderRadius: '8px',
    border: 'none',
    background: 'rgba(255, 255, 255, 0.1)',
    color: '#ffffff',
    fontSize: '16px',
    width: '100%',
    boxSizing: 'border-box',
    '@media (max-width: 768px)': {
      padding: '12px',
      fontSize: '14px',
    },
  },
  select: {
    padding: '15px',
    borderRadius: '8px',
    border: 'none',
    background: 'rgba(255, 255, 255, 0.1)',
    color: '#ffffff',
    fontSize: '16px',
    width: '100%',
    boxSizing: 'border-box',
    appearance: 'none',
    backgroundImage: 'url("data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%23FFFFFF%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E")',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 15px top 50%',
    backgroundSize: '12px auto',
    '& option': {
      backgroundColor: '#2c2c2c',
      color: '#ffffff',
    },
    '@media (max-width: 768px)': {
      padding: '12px',
      fontSize: '14px',
    },
  },
  button: {
    padding: '15px 30px',
    backgroundColor: '#333333',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    fontSize: '16px',
    fontWeight: '500',
    ':hover': {
      backgroundColor: '#444444',
    },
    '@media (max-width: 768px)': {
      padding: '12px 20px',
      fontSize: '14px',
    },
  },
  logoutButton: {
    padding: '15px 30px',
    backgroundColor: '#333333',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    fontSize: '16px',
    fontWeight: '500',
    ':hover': {
      backgroundColor: '#444444',
    },
    '@media (max-width: 768px)': {
      padding: '12px 20px',
      fontSize: '14px',
    },
  },
  deleteButton: {
    backgroundColor: '#444444',
    ':hover': {
      backgroundColor: '#555555',
    },
  },
  successButton: {
    backgroundColor: '#333333',
    ':hover': {
      backgroundColor: '#444444',
    },
  },
  table: {
    width: '100%',
    borderCollapse: 'separate',
    borderSpacing: '0',
    marginTop: '20px',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '8px',
    overflow: 'hidden',
    '@media (max-width: 768px)': {
      display: 'block',
    },
  },
  tableHeaderCell: {
    padding: '20px',
    textAlign: 'left',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    fontWeight: '500',
    fontSize: '16px',
    '@media (max-width: 768px)': {
      display: 'none',
    },
  },
  tableCell: {
    padding: '20px',
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    fontSize: '15px',
    '@media (max-width: 768px)': {
      display: 'block',
      padding: '10px',
      textAlign: 'right',
      position: 'relative',
      paddingLeft: '50%',
    },
  },
  searchContainer: {
    position: 'relative',
    width: '100%',
  },
  searchResults: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#2c2c2c',
    borderRadius: '8px',
    marginTop: '5px',
    maxHeight: '300px',
    overflowY: 'auto',
    zIndex: 1000,
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    '@media (max-width: 768px)': {
      maxHeight: '200px',
    },
  },
  searchResultItem: {
    padding: '15px',
    cursor: 'pointer',
    transition: 'background-color 0.2s ease',
    ':hover': {
      backgroundColor: '#3c3c3c',
    },
    '@media (max-width: 768px)': {
      padding: '12px',
      fontSize: '14px',
    },
  },
  photoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
    gap: '30px',
    padding: '30px',
    '@media (max-width: 768px)': {
      gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
      gap: '15px',
      padding: '15px',
    },
  },
  photoContainer: {
    position: 'relative',
    paddingBottom: '100%',
    backgroundColor: '#2c2c2c',
    borderRadius: '8px',
    overflow: 'hidden',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  photo: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  progressContainer: {
    width: '100%',
    height: '24px',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: '12px',
    overflow: 'hidden',
    marginTop: '20px',
    '@media (max-width: 768px)': {
      height: '20px',
      marginTop: '15px',
    },
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#444444',
    transition: 'width 0.3s ease',
  },
  progressText: {
    position: 'absolute',
    width: '100%',
    textAlign: 'center',
    color: '#ffffff',
    fontSize: '14px',
    lineHeight: '24px',
    '@media (max-width: 768px)': {
      fontSize: '12px',
      lineHeight: '20px',
    },
  },
  fileInput: {
    display: 'none',
  },
  selectedFilesText: {
    marginTop: '15px',
    color: '#ffffff',
    fontSize: '15px',
    textAlign: 'center',
    '@media (max-width: 768px)': {
      fontSize: '13px',
      marginTop: '10px',
    },
  },
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: '#2c2c2c',
    padding: '30px',
    borderRadius: '12px',
    maxWidth: '90%',
    maxHeight: '90%',
    overflow: 'auto',
    '@media (max-width: 768px)': {
      padding: '20px',
      maxWidth: '95%',
      maxHeight: '95%',
    },
  },
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
    marginTop: '30px',
    flexWrap: 'wrap',
    '@media (max-width: 768px)': {
      marginTop: '20px',
      gap: '8px',
    },
  },
  paginationButton: {
    padding: '10px 15px',
    backgroundColor: '#333333',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    ':hover': {
      backgroundColor: '#444444',
    },
    '@media (max-width: 768px)': {
      padding: '8px 12px',
      fontSize: '14px',
    },
  },
  activePaginationButton: {
    backgroundColor: '#444444',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '30px',
    '@media (max-width: 768px)': {
      marginBottom: '20px',
    },
  },
  headerTitle: {
    margin: 0,
  },
};

export default styles;
