const styles = {
  container: {
    display: 'flex',
    minHeight: '100vh',
    backgroundColor: '#1e1e1e',
    color: '#ffffff',
  },
  sidebar: {
    width: '250px',
    backgroundColor: '#2c2c2c',
    padding: '20px',
    boxSizing: 'border-box',
  },
  sidebarTitle: {
    marginBottom: '20px',
    textAlign: 'center',
  },
  content: {
    flex: 1,
    padding: '40px',
    boxSizing: 'border-box',
    overflowY: 'auto',
  },
  title: {
    marginBottom: '20px',
    borderBottom: '2px solid #555555',
    paddingBottom: '10px',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    marginBottom: '40px',
  },
  input: {
    padding: '10px',
    marginBottom: '20px',
    border: 'none',
    borderRadius: '4px',
    backgroundColor: '#3c3c3c',
    color: '#ffffff',
    fontSize: '16px',
    width: '100%',
    boxSizing: 'border-box',
  },
  select: {
    padding: '10px',
    marginBottom: '20px',
    border: 'none',
    borderRadius: '4px',
    backgroundColor: '#3c3c3c',
    color: '#ffffff',
  },
  button: {
    marginTop: '10px',
    padding: '10px 20px',
    backgroundColor: '#333333',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    width: '180px',
    fontSize: '14px',
    textAlign: 'center',
    display: 'inline-block',
  },
  logoutButton: {
    padding: '10px 20px',
    backgroundColor: '#333333',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    fontSize: '14px',
    width: '100%',
    marginTop: '20px',
  },
  fileInput: {
    display: 'none',
  },
  selectedFilesText: {
    marginLeft: '10px',
    fontSize: '14px',
    color: '#ffffff',
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '40px',
  },
  column: {
    width: '48%',
  },
  photoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '20px',
    marginTop: '20px',
  },
  photoContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    backgroundColor: '#2c2c2c',
    borderRadius: '8px',
    padding: '10px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  photoWrapper: {
    position: 'relative',
    width: '100%',
    paddingBottom: '100%',
    marginBottom: '10px',
  },
  photo: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    borderRadius: '4px',
    cursor: 'pointer',
  },
  selectedOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '4px',
  },
  checkmark: {
    color: '#4CAF50',
    fontSize: '48px',
    fontWeight: 'bold',
  },
  deleteButton: {
    marginTop: '10px',
    padding: '8px 16px',
    backgroundColor: '#333333',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    fontSize: '14px',
  },
  searchContainer: {
    position: 'relative',
    width: '100%',
  },
  searchResults: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#3c3c3c',
    border: '1px solid #555555',
    borderRadius: '4px',
    listStyle: 'none',
    padding: 0,
    margin: 0,
    maxHeight: '200px',
    overflowY: 'auto',
    zIndex: 1000,
  },
  searchResultItem: {
    padding: '10px',
    cursor: 'pointer',
    '&:hover': {
      backgroundColor: '#555555',
    },
  },
  modal: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    position: 'relative',
    maxWidth: '90%',
    maxHeight: '90%',
    overflow: 'hidden',
  },
  modalImage: {
    maxWidth: '100%',
    maxHeight: '90vh',
    objectFit: 'contain',
  },
  closeButton: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    padding: '5px 10px',
    backgroundColor: '#333333',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    fontSize: '16px',
  },
  navButton: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    padding: '10px 15px',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    color: 'white',
    border: 'none',
    borderRadius: '25px',
    cursor: 'pointer',
    fontSize: '16px',
  },
  progressContainer: {
    width: '100%',
    height: '20px',
    backgroundColor: '#3c3c3c',
    borderRadius: '10px',
    overflow: 'hidden',
    marginBottom: '20px',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#4CAF50',
    transition: 'width 0.5s ease-in-out',
  },
  progressText: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    color: '#ffffff',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginTop: '20px',
    backgroundColor: '#2c2c2c',
  },
  tableHeaderCell: {
    padding: '12px',
    border: '1px solid #555555',
    backgroundColor: '#333333',
    color: '#ffffff',
    fontWeight: 'bold',
    textAlign: 'left',
  },
  tableCell: {
    padding: '12px',
    border: '1px solid #555555',
    color: '#ffffff',
  },
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: '20px',
  },
  paginationButton: {
    padding: '5px 10px',
    margin: '0 5px',
    backgroundColor: '#333333',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    '&:hover': {
      backgroundColor: '#555555',
    },
  },
};

Object.assign(styles.navButton, {
  '&:first-of-type': {
    left: '10px',
  },
  '&:last-of-type': {
    right: '10px',
  },
});

export default styles;
